### ISSUE TITLE
Make the leading symbol of the nested `<li>` element a white circle.

### ISSUE THREAD

**Issue by hrfmmymt** [hrfmmymt/iiyatsu#34]
```css
ul li ul li {
  list-style-type: circle;
}
```
